### 
GET http://localhost:3001/api/filter?celiac=false Content-Type: application/json

###

GET http://localhost:3001/api/filter?price=15 Content-Type: application/json

###

GET http://localhost:3001/api/filter?category=Platos%20principales Content-Type: application/json

###

